### ISSUE TITLE
Twitch app issue

### ISSUE THREAD

**Issue by Laserm4n** [awtrix/AWTRIX2.0-Apps#30]
Hi few dais ago my awtrix have problems to show twitch app, i delete all mi apps and reinstall now and twitch app can`t login.
Shows a pop up window and login succeful but in reality after refresh main window is not loged in.
Anyone knows the problem?

**Comment by Synoyx** [comment]
Same for me, successfully logged in, but once I refresh the page it ask for me to log again ... 
Nothin meaningfull in the logs, just keep saying "3:13:08 PM      Twitch is not set up!" on each refresh

When I wasn't logged, had the error "3:10:43 PM      Error while downloading data 3 for Twitch
3:10:43 PM      {"error":"Unauthorized","status":401,"message":"OAuth token is missing"}"


I have a critical error in the AWTRIX HMI : "  -->  Error in draw progress:
        (RuntimeException) java.lang.RuntimeException: Object should first be initialized (List)."
But I think it's because the twitch app can't draw anything ?

**Comment by Synoyx** [comment]
So I did it.
You need to generate a client secret & code, and compile again the twitch app with these values.
On your twitch developper account, you need to authorize the app to access datas.

Not easy, but it works now for me

**Comment by Laserm4n** [comment]
You can show me more? i'm really noob xD

**Comment by Blueforcer** [comment]
fixed with latest twitch update
